# Generated by Django 5.2.5 on 2025-09-04 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='quotes',
            options={'verbose_name': 'Цитата', 'verbose_name_plural': 'Цитаты'},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'verbose_name': 'Источник', 'verbose_name_plural': 'Источники'},
        ),
        migrations.AddField(
            model_name='quotes',
            name='normalize_text',
            field=models.TextField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='dislikes',
            field=models.PositiveIntegerField(default=0, verbose_name='Дизлайки'),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Лайки'),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quotes.source', verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='text_quotes',
            field=models.TextField(unique=True, verbose_name='Цитата'),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='weight',
            field=models.IntegerField(default=1, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='source',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quotes.categories', verbose_name='Категория'),
        ),
    ]
