# Generated by Django 5.2.5 on 2025-09-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_alter_categories_options_alter_quotes_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='normalize_text',
            field=models.TextField(editable=False, unique=True),
        ),
    ]
